-- Seed hardcoded abbreviations into the content table so that all
-- abbreviations are managed in the database (namespace: abbr.list).
-- ON CONFLICT DO NOTHING preserves any existing custom values.

INSERT INTO public.content (namespace, key, value, ctype) VALUES
  ('abbr.list', 'OEL',      'Occupational Exposure Limit — grenswaarde voor beroepsmatige blootstelling', 'plain'),
  ('abbr.list', 'OELV',     'Occupational Exposure Limit Value — grenswaarde voor beroepsmatige blootstelling', 'plain'),
  ('abbr.list', 'TGG',      'Tijdgewogen gemiddelde', 'plain'),
  ('abbr.list', 'CLP',      'Classification, Labelling and Packaging — Verordening EG 1272/2008', 'plain'),
  ('abbr.list', 'VIB',      'Veiligheidsinformatieblad', 'plain'),
  ('abbr.list', 'SDS',      'Safety Data Sheet — veiligheidsinformatieblad', 'plain'),
  ('abbr.list', 'CMR',      'Carcinogeen, Mutageen of Reproductietoxisch', 'plain'),
  ('abbr.list', 'ATEX',     'ATmosphères EXplosibles — explosieve atmosferen (Arbobesluit hfst. 3 par. 2a)', 'plain'),
  ('abbr.list', 'LEL',      'Lower Explosive Limit — laagste explosieve concentratie (% vol)', 'plain'),
  ('abbr.list', 'UEL',      'Upper Explosive Limit — hoogste explosieve concentratie (% vol)', 'plain'),
  ('abbr.list', 'ARIE',     'Aanvullende Risico-Inventarisatie en -Evaluatie — grote hoeveelheden gevaarlijke stoffen (Arbobesluit hfst. 2 afd. 2)', 'plain'),
  ('abbr.list', 'RIE',      'Risico-Inventarisatie en -Evaluatie (Arbowet art. 5)', 'plain'),
  ('abbr.list', 'REACH',    'Registration, Evaluation, Authorisation and restriction of CHemicals — Verordening EG 1907/2006', 'plain'),
  ('abbr.list', 'IUPAC',    'International Union of Pure and Applied Chemistry', 'plain'),
  ('abbr.list', 'DNEL',     'Derived No-Effect Level — grenswaarde afgeleid uit REACH-registratiedossier', 'plain'),
  ('abbr.list', 'NLA',      'NLA-handelingskader "Werken met gevaarlijke stoffen" (Nationaal Loket Arbodeskundigen)', 'plain'),
  ('abbr.list', 'SEG',      'Similar Exposure Group — groep medewerkers met vergelijkbare blootstelling', 'plain'),
  ('abbr.list', 'LEV',      'Lokale Exhaust Ventilatie — bronafzuiging', 'plain'),
  ('abbr.list', 'ACH',      'Air Changes per Hour — luchtverversingen per uur', 'plain'),
  ('abbr.list', 'PPE',      'Personal Protective Equipment — persoonlijke beschermingsmiddelen', 'plain'),
  ('abbr.list', 'PBM',      'Persoonlijke beschermingsmiddelen', 'plain'),
  ('abbr.list', 'HOVd',     'Hogere Veiligheidskundige (deskundigheidsniveau d)', 'plain'),
  ('abbr.list', 'HEG',      'Homogene Blootstellingsgroep — groep medewerkers met vergelijkbare geluidblootstelling (NEN-EN-ISO 9612:2025 §7.2)', 'plain'),
  ('abbr.list', 'LAV',      'Lagere Actiewaarde geluid — 80 dB(A) dagelijks / 135 dB(C) piek — Arbobesluit art. 6.6 lid 1', 'plain'),
  ('abbr.list', 'UAV',      'Bovenste Actiewaarde geluid — 85 dB(A) dagelijks / 137 dB(C) piek — Arbobesluit art. 6.6 lid 1', 'plain'),
  ('abbr.list', 'GW',       'Grenswaarde geluid — 87 dB(A) dagelijks / 140 dB(C) piek — Arbobesluit art. 6.6 lid 2', 'plain'),
  ('abbr.list', 'SNR',      'Single Number Rating — eén-getal beschermingswaarde gehoorbeschermer (EN 352/EN 458:2016)', 'plain'),
  ('abbr.list', 'OB',       'Octaafbandanalyse — meting van het geluidniveau per octaafband (63–8000 Hz), optioneel voor EN 458:2016 methode 3', 'plain'),
  ('abbr.list', 'APF',      'Assumed Protection Factor — aangenomen beschermingsfactor in de praktijk (EN 458:2016)', 'plain'),
  ('abbr.list', 'SLM',      'Sound Level Meter — geluidniveaumeter (IEC 61672-1)', 'plain'),
  ('abbr.list', 'NEN9612',  'NEN-EN-ISO 9612:2025 — Akoestiek — Bepaling van de blootstelling aan lawaai op de werkplek (Third edition)', 'plain'),
  ('abbr.list', 'LEX',      'L_EX,8h — dagelijkse geluidblootstelling genormeerd naar 8 uur, A-gewogen (NEN-EN-ISO 9612:2025)', 'plain'),
  ('abbr.list', 'NPR3438',  'NPR 3438:2007 — Ergonomie: Geluidhinder op de arbeidsplaats — Bepaling van de mate van verstoring van communicatie en concentratie (Nederlandse Praktijkrichtlijn)', 'plain'),
  ('abbr.list', 'PMV',      'Predicted Mean Vote — voorspelde gemiddelde thermische waardering (ISO 7730:2025 vgl. 1)', 'plain'),
  ('abbr.list', 'PPD',      'Predicted Percentage Dissatisfied — voorspeld percentage ontevreden medewerkers (ISO 7730:2025 vgl. 2)', 'plain'),
  ('abbr.list', 'DR',       'Draught Rate — tochtpercentage; kans op thermisch ongemak door luchtstroom (ISO 7730:2025 §6.2)', 'plain'),
  ('abbr.list', 'WBGT',     'Wet Bulb Globe Temperature — natteboltemperatuur voor hittestressscreening (ISO 7243:2017)', 'plain'),
  ('abbr.list', 'PHS',      'Predicted Heat Strain — voorspelde warmtebelasting; gedetailleerd hittestressmodel (ISO 7933:2023)', 'plain'),
  ('abbr.list', 'IREQ',     'Insulation REQuired — benodigde kledinginsulatie voor thermisch evenwicht bij koudestress (ISO 11079:2007)', 'plain'),
  ('abbr.list', 'CAV',      'Clothing Adjustment Value — kledingcorrectiewaarde voor WBGT bij beschermende kleding (ISO 7243:2017 Tabel B.2)', 'plain'),
  ('abbr.list', 'BG',       'Blootstellingsgroep — groep medewerkers met vergelijkbare thermische blootstelling (analoog SEG in klimaatonderzoek)', 'plain'),
  ('abbr.list', 'ISO7730',  'ISO 7730:2025 — Ergonomics of the thermal environment — Analytical determination and interpretation of thermal comfort (4th edition)', 'plain'),
  ('abbr.list', 'ISO7243',  'ISO 7243:2017 — Ergonomics of the thermal environment — Assessment of heat stress using the WBGT index (3rd edition)', 'plain'),
  ('abbr.list', 'ISO7933',  'ISO 7933:2023 — Ergonomics of the thermal environment — Analytical determination and interpretation of heat stress using calculation of the predicted heat strain (3rd edition)', 'plain'),
  ('abbr.list', 'ISO11079', 'ISO 11079:2007 — Ergonomics of the thermal environment — Determination and interpretation of cold stress using required clothing insulation (IREQ) and local cooling effects', 'plain'),
  ('abbr.list', 'ISO7726',  'ISO 7726:1998 — Ergonomics of the thermal environment — Instruments for measuring physical quantities', 'plain')
ON CONFLICT (namespace, key) DO NOTHING;
